title = "COMP6[84]43 Slides"
languageCode = "en-au"

enableEmoji=true

relativeURLs = true
theme = "reveal-hugo"

[markup.goldmark.rendered]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true